# Generated by Django 3.1.4 on 2021-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_dislikes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
