# Generated by Django 3.1.4 on 2021-01-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210129_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='abusereports',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
