# Generated by Django 3.1.4 on 2020-12-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='voting',
        ),
        migrations.RemoveField(
            model_name='votedusers',
            name='option',
        ),
        migrations.RemoveField(
            model_name='votedusers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='user',
        ),
        migrations.DeleteModel(
            name='AbuseReports',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='VotedUsers',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
